resolver 127.0.0.11 ipv6=off valid=10s;

server {
  listen 80;
  server_name webvakwerk.localtest.me webvakwerk.nl www.webvakwerk.nl;
  client_max_body_size 25m;

  location /api/ {
    set $api_upstream http://api:3001;
    client_max_body_size 25m;
    proxy_pass $api_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
  }

  location / {
    set $public_upstream http://public-web:80;
    proxy_pass $public_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
  }
}

server {
  listen 80;
  server_name portal.webvakwerk.localtest.me portal.webvakwerk.nl;
  client_max_body_size 25m;

  location /api/ {
    set $api_upstream http://api:3001;
    client_max_body_size 25m;
    proxy_pass $api_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
  }

  location / {
    set $portal_upstream http://portal-web:80;
    proxy_pass $portal_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
  }
}
